[package]
name = "rmirror"
version = "0.1.0"
authors = ["Jsi1v4 <git@jsi1v4.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
serde = "1.0.126"
serde_json = "1.0"
